apiVersion: apps/v1
kind: Deployment
metadata:
  name: jevic-app-deploy
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: jevic-app
  template:
    metadata:
      labels:
        app: jevic-app
    spec:
      containers:
        - name: jevic-app
          image: jevic/app:v1
          ports:
            - name: http
              containerPort: 80
